const dadosPortos = {
  "Tabela 00 - Cadastro": [
    {
      "Zona portuÃ¡ria": "Porto Organizado de Santos",
      "UF": "SP",
      "Obj. de ConcessÃ£o": "TECON 10",
      "Tipo": "Arrendamento",
      "CAPEX Total": 6454903000,
      "CAPEX Executado": 40473675.0,
      "% CAPEX Executado": 0.006270222031221848,
      "Data de assinatura do contrato": null,
      "DescriÃ§Ã£o": "Terminal destinado Ã  movimentaÃ§Ã£o e armazenagem de carga conteinerizada e carga geral.",
      "Latitude": -23.926132,
      "Longitude": -46.34027
    },
    {
      "Zona portuÃ¡ria": "NÃ£o se aplica",
      "UF": "MT; MS",
      "Obj. de ConcessÃ£o": "Hidrovia do Paraguai",
      "Tipo": "ConcessÃ£o",
      "CAPEX Total": 63796000,
      "CAPEX Executado": null,
      "% CAPEX Executado": 0.0,
      "Data de assinatura do contrato": null,
      "DescriÃ§Ã£o": "Hidrovia no trecho brasileiro fazendo divisa com Paraguai e BolÃ­via.",
      "Latitude": null,
      "Longitude": null
    },
    {
      "Zona portuÃ¡ria": "Porto Organizado de MaceiÃ³",
      "UF": "AL",
      "Obj. de ConcessÃ£o": "TPM MacÃ©io",
      "Tipo": "Arrendamento",
      "CAPEX Total": 1978000,
      "CAPEX Executado": null,
      "% CAPEX Executado": 0.0,
      "Data de assinatura do contrato": null,
      "DescriÃ§Ã£o": "Terminal destinado a movimentaÃ§Ã£o de passageiros.",
      "Latitude": null,
      "Longitude": null
    },
    {
      "Zona portuÃ¡ria": "Porto Organizado do Rio de Janeiro",
      "UF": "RJ",
      "Obj. de ConcessÃ£o": "RDJ07",
      "Tipo": "Arrendamento",
      "CAPEX Total": 101741000,
      "CAPEX Executado": null,
      "% CAPEX Executado": 0.0,
      "Data de assinatura do contrato": null,
      "DescriÃ§Ã£o": "Terminal portuÃ¡rio destinado Ã  movimentaÃ§Ã£o e armazenagem de carga para apoio logÃ­stico Offshore.",
      "Latitude": -22.896621,
      "Longitude": -43.209639
    },
    {
      "Zona portuÃ¡ria": "NÃ£o se aplica",
      "UF": "PR",
      "Obj. de ConcessÃ£o": "Canal de ParanaguÃ¡",
      "Tipo": "ConcessÃ£o",
      "CAPEX Total": 1226475000,
      "CAPEX Executado": null,
      "% CAPEX Executado": 0.0,
      "Data de assinatura do contrato": "2026-02-20",
      "DescriÃ§Ã£o": "Acesso aquaviÃ¡rio (canal de acesso) ao Porto de ParanaguÃ¡.",
      "Latitude": -25.492142,
      "Longitude": -48.479187
    },
    {
      "Zona portuÃ¡ria": "Porto Organizado de SÃ£o SebastiÃ£o",
      "UF": "SP",
      "Obj. de ConcessÃ£o": "SSB01",
      "Tipo": "Arrendamento",
      "CAPEX Total": 656085000,
      "CAPEX Executado": null,
      "% CAPEX Executado": 0.0,
      "Data de assinatura do contrato": null,
      "DescriÃ§Ã£o": "PÃ¡tio de cargas para movimentaÃ§Ã£o de carga conteinerizada, dentre outras.",
      "Latitude": -23.812704,
      "Longitude": -45.400052
    }
  ],
  "Tabela 01 - ServiÃ§os": [
    {
      "Zona portuÃ¡ria": "NÃ£o se aplica",
      "UF": "PR",
      "Obj. de ConcessÃ£o": "Canal de ParanaguÃ¡",
      "Tipo de ServiÃ§o": "CMO",
      "Fase": "1Âª",
      "ServiÃ§o": "Dragagem de ImplantaÃ§Ã£o de canal",
      "DescriÃ§Ã£o do serviÃ§o": "EvoluÃ§Ã£o para  13,3m",
      "Prazo inÃ­cio (anos)": 3,
      "Data de inÃ­cio": "2028-02-20",
      "Prazo final (anos)": 3.0,
      "Data final": "2029-02-19",
      "Fonte (Prazo)": "EVTEA - Plano de ExploraÃ§Ã£o",
      "% de CAPEX para o serviÃ§o": 0.1,
      "CAPEX do ServiÃ§o (total)": 122647500,
      "CAPEX do ServiÃ§o (exec.)": 40473675.0,
      "% CAPEX exec.": 0.33,
      "Fonte (% do CAPEX)": "Estimado"
    },
    {
      "Zona portuÃ¡ria": "NÃ£o se aplica",
      "UF": "PR",
      "Obj. de ConcessÃ£o": "Canal de ParanaguÃ¡",
      "Tipo de ServiÃ§o": "CMO",
      "Fase": "1Âª",
      "ServiÃ§o": "Dragagem de ImplantaÃ§Ã£o de berÃ§os",
      "DescriÃ§Ã£o do serviÃ§o": "a) berÃ§os 201-215; e b) berÃ§os 216-218",
      "Prazo inÃ­cio (anos)": 3,
      "Data de inÃ­cio": "2028-02-20",
      "Prazo final (anos)": 5.0,
      "Data final": "2031-02-19",
      "Fonte (Prazo)": "EVTEA - Plano de ExploraÃ§Ã£o",
      "% de CAPEX para o serviÃ§o": 0.1,
      "CAPEX do ServiÃ§o (total)": 122647500,
      "CAPEX do ServiÃ§o (exec.)": null,
      "% CAPEX exec.": 0.0,
      "Fonte (% do CAPEX)": "Estimado"
    },
    {
      "Zona portuÃ¡ria": "NÃ£o se aplica",
      "UF": "PR",
      "Obj. de ConcessÃ£o": "Canal de ParanaguÃ¡",
      "Tipo de ServiÃ§o": "Disponibilidade de Infraestrutura",
      "Fase": "1Âª",
      "ServiÃ§o": "Alargamento de bacia de evoluÃ§Ã£o",
      "DescriÃ§Ã£o do serviÃ§o": "Trechos Charlie 1 e 3",
      "Prazo inÃ­cio (anos)": 3,
      "Data de inÃ­cio": "2028-02-20",
      "Prazo final (anos)": 3.0,
      "Data final": "2029-02-19",
      "Fonte (Prazo)": "EVTEA - Plano de ExploraÃ§Ã£o",
      "% de CAPEX para o serviÃ§o": 0.1,
      "CAPEX do ServiÃ§o (total)": 122647500,
      "CAPEX do ServiÃ§o (exec.)": null,
      "% CAPEX exec.": 0.0,
      "Fonte (% do CAPEX)": "Estimado"
    },
    {
      "Zona portuÃ¡ria": "NÃ£o se aplica",
      "UF": "PR",
      "Obj. de ConcessÃ£o": "Canal de ParanaguÃ¡",
      "Tipo de ServiÃ§o": "Disponibilidade de Infraestrutura",
      "Fase": "1Âª",
      "ServiÃ§o": "Derrocamento",
      "DescriÃ§Ã£o do serviÃ§o": "Pedra da Palangana - retificaÃ§Ã£o do canal de acesso",
      "Prazo inÃ­cio (anos)": 3,
      "Data de inÃ­cio": "2028-02-20",
      "Prazo final (anos)": 5.0,
      "Data final": "2031-02-19",
      "Fonte (Prazo)": "EVTEA - Plano de ExploraÃ§Ã£o",
      "% de CAPEX para o serviÃ§o": 0.25,
      "CAPEX do ServiÃ§o (total)": 306618750,
      "CAPEX do ServiÃ§o (exec.)": null,
      "% CAPEX exec.": 0.0,
      "Fonte (% do CAPEX)": "Estimado"
    },
    {
      "Zona portuÃ¡ria": "NÃ£o se aplica",
      "UF": "PR",
      "Obj. de ConcessÃ£o": "Canal de ParanaguÃ¡",
      "Tipo de ServiÃ§o": "CMO",
      "Fase": "2Âª",
      "ServiÃ§o": "Dragagem de ImplantaÃ§Ã£o de canal",
      "DescriÃ§Ã£o do serviÃ§o": "EvoluÃ§Ã£o para e 15,5m",
      "Prazo inÃ­cio (anos)": 3,
      "Data de inÃ­cio": "2028-02-20",
      "Prazo final (anos)": 5.0,
      "Data final": "2031-02-19",
      "Fonte (Prazo)": "EVTEA - Plano de ExploraÃ§Ã£o",
      "% de CAPEX para o serviÃ§o": 0.1,
      "CAPEX do ServiÃ§o (total)": 122647500,
      "CAPEX do ServiÃ§o (exec.)": null,
      "% CAPEX exec.": 0.0,
      "Fonte (% do CAPEX)": "Estimado"
    },
    {
      "Zona portuÃ¡ria": "NÃ£o se aplica",
      "UF": "PR",
      "Obj. de ConcessÃ£o": "Canal de ParanaguÃ¡",
      "Tipo de ServiÃ§o": "CMO",
      "Fase": "2Âª",
      "ServiÃ§o": "Dragagem de ImplantaÃ§Ã£o de berÃ§os",
      "DescriÃ§Ã£o do serviÃ§o": "a) berÃ§os 216-218; b) Pier L; c) PÃ­er F; e d) PÃ­er T",
      "Prazo inÃ­cio (anos)": 3,
      "Data de inÃ­cio": "2028-02-20",
      "Prazo final (anos)": 5.0,
      "Data final": "2031-02-19",
      "Fonte (Prazo)": "EVTEA - Plano de ExploraÃ§Ã£o",
      "% de CAPEX para o serviÃ§o": 0.1,
      "CAPEX do ServiÃ§o (total)": 122647500,
      "CAPEX do ServiÃ§o (exec.)": null,
      "% CAPEX exec.": 0.0,
      "Fonte (% do CAPEX)": "Estimado"
    },
    {
      "Zona portuÃ¡ria": "NÃ£o se aplica",
      "UF": "PR",
      "Obj. de ConcessÃ£o": "Canal de ParanaguÃ¡",
      "Tipo de ServiÃ§o": "CMO",
      "Fase": "2Âª",
      "ServiÃ§o": "Derrocamento",
      "DescriÃ§Ã£o do serviÃ§o": "Pedra da Palangana - integraÃ§Ã£o da Ã¡rea Ã  bacia de evoluÃ§Ã£o e manobras",
      "Prazo inÃ­cio (anos)": 3,
      "Data de inÃ­cio": "2028-02-20",
      "Prazo final (anos)": 5.0,
      "Data final": "2031-02-19",
      "Fonte (Prazo)": "EVTEA - Plano de ExploraÃ§Ã£o",
      "% de CAPEX para o serviÃ§o": 0.24,
      "CAPEX do ServiÃ§o (total)": 294354000,
      "CAPEX do ServiÃ§o (exec.)": null,
      "% CAPEX exec.": 0.0,
      "Fonte (% do CAPEX)": "Estimado"
    },
    {
      "Zona portuÃ¡ria": "NÃ£o se aplica",
      "UF": "PR",
      "Obj. de ConcessÃ£o": "Canal de ParanaguÃ¡",
      "Tipo de ServiÃ§o": "Disponibilidade de Infraestrutura",
      "Fase": "2Âª",
      "ServiÃ§o": "ImplantaÃ§Ã£o de Sistema",
      "DescriÃ§Ã£o do serviÃ§o": "Sistemas de Gerenciamento do TrÃ¡fego (VTS/VTMIS)",
      "Prazo inÃ­cio (anos)": 5,
      "Data de inÃ­cio": "2030-02-19",
      "Prazo final (anos)": null,
      "Data final": null,
      "Fonte (Prazo)": "EVTEA - Plano de ExploraÃ§Ã£o",
      "% de CAPEX para o serviÃ§o": 0.01,
      "CAPEX do ServiÃ§o (total)": 12264750,
      "CAPEX do ServiÃ§o (exec.)": null,
      "% CAPEX exec.": 0.0,
      "Fonte (% do CAPEX)": "Estimado"
    }
  ],
  "Tabela 02 - Acompanhamento": [
    {
      "Zona portuÃ¡ria": "NÃ£o se aplica",
      "UF": "PR",
      "Obj. de ConcessÃ£o": "Canal de ParanaguÃ¡",
      "Tipo de ServiÃ§o": "CMO",
      "Fase": "1Âª",
      "ServiÃ§o": "Dragagem de ImplantaÃ§Ã£o de canal",
      "DescriÃ§Ã£o": "EvoluÃ§Ã£o para  13,3m",
      "% executada": 0.1,
      "Valor executado": 12264750,
      "Data da atualizaÃ§Ã£o": "2029-06-06",
      "ResponsÃ¡vel": "Mateus",
      "Cargo": "Analista",
      "Setor": "PPI",
      "Riscos Relacionados (Tipo)": "Meio Ambiente",
      "Riscos Relacionados (DescriÃ§Ã£o)": "Parte do trecho estÃ¡ com pendÃªncia de licenciamento ambiental"
    },
    {
      "Zona portuÃ¡ria": "NÃ£o se aplica",
      "UF": "PR",
      "Obj. de ConcessÃ£o": "Canal de ParanaguÃ¡",
      "Tipo de ServiÃ§o": "CMO",
      "Fase": "1Âª",
      "ServiÃ§o": "Dragagem de ImplantaÃ§Ã£o de canal",
      "DescriÃ§Ã£o": "EvoluÃ§Ã£o para  13,3m",
      "% executada": 0.15,
      "Valor executado": 18397125,
      "Data da atualizaÃ§Ã£o": "2030-06-10",
      "ResponsÃ¡vel": "Mateus",
      "Cargo": "Analista",
      "Setor": "PPI",
      "Riscos Relacionados (Tipo)": "Financeiro",
      "Riscos Relacionados (DescriÃ§Ã£o)": "ConcessionÃ¡ria estÃ¡ com problemas financeiros para continuidade"
    },
    {
      "Zona portuÃ¡ria": "NÃ£o se aplica",
      "UF": "PR",
      "Obj. de ConcessÃ£o": "Canal de ParanaguÃ¡",
      "Tipo de ServiÃ§o": "CMO",
      "Fase": "1Âª",
      "ServiÃ§o": "Dragagem de ImplantaÃ§Ã£o de canal",
      "DescriÃ§Ã£o": "EvoluÃ§Ã£o para  13,3m",
      "% executada": 0.08,
      "Valor executado": 9811800,
      "Data da atualizaÃ§Ã£o": "2031-10-08",
      "ResponsÃ¡vel": "Mateus",
      "Cargo": "Analista",
      "Setor": "PPI",
      "Riscos Relacionados (Tipo)": "Meio Ambiente",
      "Riscos Relacionados (DescriÃ§Ã£o)": "Ainda nÃ£o foi obtida LicenÃ§a Operacional"
    }
  ],
  "Auxiliar": [
    {
      "Unnamed: 0": null,
      "Unnamed: 1": "Tabela 00 - Cadastro",
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null,
      "Unnamed: 10": null,
      "Unnamed: 11": null,
      "Unnamed: 12": null
    },
    {
      "Unnamed: 0": "DescriÃ§Ã£o Geral",
      "Unnamed: 1": "Trata-se do cadastro inicial de cada objeto especÃ­fico de concessÃ£o. Vai se referir a chave primÃ¡ria para relaÃ§Ã£o com as demais tabelas.",
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null,
      "Unnamed: 10": null,
      "Unnamed: 11": null,
      "Unnamed: 12": null
    },
    {
      "Unnamed: 0": "Coluna",
      "Unnamed: 1": "Zona portuÃ¡ria",
      "Unnamed: 2": "UF",
      "Unnamed: 3": "Obj. de ConcessÃ£o",
      "Unnamed: 4": "Tipo",
      "Unnamed: 5": "CAPEX Total",
      "Unnamed: 6": "Data de assinatura do contrato",
      "Unnamed: 7": "DescriÃ§Ã£o",
      "Unnamed: 8": "Coordenada E (UTM)",
      "Unnamed: 9": "Coordenada S (UTM)",
      "Unnamed: 10": "Fuso",
      "Unnamed: 11": null,
      "Unnamed: 12": null
    },
    {
      "Unnamed: 0": "DescriÃ§Ã£o do tipo de dado",
      "Unnamed: 1": "Nome da zona portuÃ¡ria a ser concedida, conforme exemplos abaixo. Aceita textos curtos.",
      "Unnamed: 2": "Unidade federativa do porto, aceita uma ou mais unidades federativas.",
      "Unnamed: 3": "Descrever o objeto especÃ­fico da ConcessÃ£o, que pode ser um Terminal, o Canal, a AdministraÃ§Ã£o do porto.",
      "Unnamed: 4": "FIXO (ConcessÃ£o; Arrendamento ou AutorizaÃ§Ã£o)",
      "Unnamed: 5": "Valor total do CAPEX previsto nos estudos para toda concessÃ£o.",
      "Unnamed: 6": "Data da assinatura do contrato.",
      "Unnamed: 7": "DescriÃ§Ã£o livre do objeto de concessÃ£o",
      "Unnamed: 8": "Para visualizaÃ§Ã£o (SIG)",
      "Unnamed: 9": "Para visualizaÃ§Ã£o (SIG)",
      "Unnamed: 10": "Para visualizaÃ§Ã£o (SIG)",
      "Unnamed: 11": null,
      "Unnamed: 12": null
    },
    {
      "Unnamed: 0": "Dados exemplificativos",
      "Unnamed: 1": "Porto Organizado de Santos",
      "Unnamed: 2": "SP",
      "Unnamed: 3": "TECON 10",
      "Unnamed: 4": "ConcessÃ£o",
      "Unnamed: 5": "Ex:",
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null,
      "Unnamed: 10": null,
      "Unnamed: 11": null,
      "Unnamed: 12": null
    },
    {
      "Unnamed: 0": null,
      "Unnamed: 1": "NÃ£o se aplica",
      "Unnamed: 2": "MT; MS",
      "Unnamed: 3": "Hidrovia do Paraguai",
      "Unnamed: 4": "Arrendamento",
      "Unnamed: 5": 1000000000,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null,
      "Unnamed: 10": null,
      "Unnamed: 11": null,
      "Unnamed: 12": null
    },
    {
      "Unnamed: 0": null,
      "Unnamed: 1": "Porto Organizado de MaceiÃ³",
      "Unnamed: 2": "AL",
      "Unnamed: 3": "TPM MacÃ©io",
      "Unnamed: 4": "AutorizaÃ§Ã£o",
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null,
      "Unnamed: 10": null,
      "Unnamed: 11": null,
      "Unnamed: 12": null
    },
    {
      "Unnamed: 0": null,
      "Unnamed: 1": "Porto Organizado do Rio de Janeiro",
      "Unnamed: 2": "RJ",
      "Unnamed: 3": "RDJ07",
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null,
      "Unnamed: 10": null,
      "Unnamed: 11": null,
      "Unnamed: 12": null
    },
    {
      "Unnamed: 0": null,
      "Unnamed: 1": "NÃ£o se aplica",
      "Unnamed: 2": "PR",
      "Unnamed: 3": "Canal de ParanaguÃ¡",
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null,
      "Unnamed: 10": null,
      "Unnamed: 11": null,
      "Unnamed: 12": null
    },
    {
      "Unnamed: 0": "RestriÃ§Ãµes",
      "Unnamed: 1": "Nomes curtos (buscar padronizaÃ§Ã£o, talvez um autocompletar para facilitar na hora do preenchimento, pois poderÃ£o existir mais de objeto de concessÃ£o no mesmo porto).",
      "Unnamed: 2": "Siglas dos estados, uma ou mais.",
      "Unnamed: 3": "Nomes curtos",
      "Unnamed: 4": "3 opÃ§Ãµes unicas",
      "Unnamed: 5": "MonetÃ¡rio (Real)",
      "Unnamed: 6": "Data: (11/11/2011)",
      "Unnamed: 7": "Livre",
      "Unnamed: 8": "NÃºmero",
      "Unnamed: 9": "NÃºmero",
      "Unnamed: 10": "NÃºmero",
      "Unnamed: 11": null,
      "Unnamed: 12": null
    },
    {
      "Unnamed: 0": null,
      "Unnamed: 1": "Tabela 01 - ServiÃ§os",
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null,
      "Unnamed: 10": null,
      "Unnamed: 11": null,
      "Unnamed: 12": null
    },
    {
      "Unnamed: 0": "DescriÃ§Ã£o geral",
      "Unnamed: 1": "Trata-se do banco de dados onde serÃ£o cadastrados os serviÃ§os a serem realizados nos objetos de concessÃ£o. Cada serviÃ§o serÃ¡ um registro e um conjunto de serviÃ§o estarÃ¡ vinculado a um registro da Tabela 00.",
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null,
      "Unnamed: 10": null,
      "Unnamed: 11": null,
      "Unnamed: 12": null
    },
    {
      "Unnamed: 0": "Coluna",
      "Unnamed: 1": "Tipo de ServiÃ§o",
      "Unnamed: 2": "Fase",
      "Unnamed: 3": "ServiÃ§o",
      "Unnamed: 4": "DescriÃ§Ã£o",
      "Unnamed: 5": "Prazo inÃ­cio (anos)",
      "Unnamed: 6": "Data de inÃ­cio",
      "Unnamed: 7": "Prazo final (anos)",
      "Unnamed: 8": "Data final",
      "Unnamed: 9": "Fonte (Prazo)",
      "Unnamed: 10": "% de CAPEX para o serviÃ§o",
      "Unnamed: 11": "CAPEX do ServiÃ§o",
      "Unnamed: 12": "Fonte (% do CAPEX)"
    },
    {
      "Unnamed: 0": "DescriÃ§Ã£o do tipo de dado",
      "Unnamed: 1": "Trata-se de uma classificaÃ§Ã£o MACRO do serviÃ§o. Uma classe mais genÃ©rica.",
      "Unnamed: 2": "1Âª, 2Âª, 3Âª (...)",
      "Unnamed: 3": "Uma classificaÃ§Ã£o ainda geral, mas mais detalhada do serviÃ§o.",
      "Unnamed: 4": "DescriÃ§Ã£o mais livre que tornarÃ¡ o serviÃ§o Ãºnico.",
      "Unnamed: 5": "NÂº do ano acrescido de de \"i\" ou \"f\". \"i\" refere-se ao inÃ­cio do ano e \"f\" ao final.",
      "Unnamed: 6": "SerÃ¡ calculada considerando o prazo e a data de assinatura do contrato (Data + nÂº de anos).",
      "Unnamed: 7": "NÂº do ano acrescido de de \"i\" ou \"f\". \"i\" refere-se ao inÃ­cio do ano e \"f\" ao final.",
      "Unnamed: 8": "SerÃ¡ calculada considerando o prazo e a data de assinatura do contrato (Data + nÂº de anos).",
      "Unnamed: 9": "De onde foi tirado as informaÃ§Ãµes.",
      "Unnamed: 10": "% do CAPEX estimada para o serviÃ§o.",
      "Unnamed: 11": "Valor do CAPEX considerando a % estimada",
      "Unnamed: 12": "Fonte da % do CAPEX, pode ser \"Estimado\" ou de algum estudo."
    },
    {
      "Unnamed: 0": "Dados exemplificativos",
      "Unnamed: 1": "CMO",
      "Unnamed: 2": "1Âª",
      "Unnamed: 3": "Dragagem de ImplantaÃ§Ã£o de berÃ§os",
      "Unnamed: 4": null,
      "Unnamed: 5": "3-i",
      "Unnamed: 6": "DATA+[PRAZO-1ANO+1DIA] -> Se \"i\"",
      "Unnamed: 7": "3-i",
      "Unnamed: 8": "DATA+[PRAZO-1ANO+1DIA] -> Se \"i\"",
      "Unnamed: 9": "EVTEA - Plano de ExploraÃ§Ã£o",
      "Unnamed: 10": null,
      "Unnamed: 11": null,
      "Unnamed: 12": null
    },
    {
      "Unnamed: 0": null,
      "Unnamed: 1": "Disponibilidade de Infraestrutura",
      "Unnamed: 2": "2Âª",
      "Unnamed: 3": "Alargamento de bacia de evoluÃ§Ã£o",
      "Unnamed: 4": null,
      "Unnamed: 5": "3-f",
      "Unnamed: 6": "DATA+[PRAZO] -> Se \"f\"",
      "Unnamed: 7": "3-f",
      "Unnamed: 8": "DATA+[PRAZO] -> Se \"f\"",
      "Unnamed: 9": null,
      "Unnamed: 10": null,
      "Unnamed: 11": null,
      "Unnamed: 12": null
    },
    {
      "Unnamed: 0": null,
      "Unnamed: 1": null,
      "Unnamed: 2": null,
      "Unnamed: 3": "Derrocamento",
      "Unnamed: 4": null,
      "Unnamed: 5": "4-f",
      "Unnamed: 6": null,
      "Unnamed: 7": "4-f",
      "Unnamed: 8": null,
      "Unnamed: 9": null,
      "Unnamed: 10": null,
      "Unnamed: 11": null,
      "Unnamed: 12": null
    },
    {
      "Unnamed: 0": "RestriÃ§Ãµes",
      "Unnamed: 1": "Lista suspensa com possibilidade de acrescentar opÃ§Ãµes.",
      "Unnamed: 2": "Conforme formato exemplificado.",
      "Unnamed: 3": "Lista suspensa com possibilidade de acrescentar opÃ§Ãµes.",
      "Unnamed: 4": "DescriÃ§Ã£o livre.",
      "Unnamed: 5": "Conforme formato exemplificado.",
      "Unnamed: 6": "AutomÃ¡tico",
      "Unnamed: 7": "Conforme formato exemplificado.",
      "Unnamed: 8": "AutomÃ¡tico",
      "Unnamed: 9": "Lista suspensa com possibilidade de acrescentar opÃ§Ãµes.",
      "Unnamed: 10": "Porcentagem",
      "Unnamed: 11": "AutomÃ¡tico",
      "Unnamed: 12": "Lista suspensa com possibilidade de acrescentar opÃ§Ãµes."
    },
    {
      "Unnamed: 0": null,
      "Unnamed: 1": "Tabela 02 - Acompanhamento",
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null,
      "Unnamed: 10": null,
      "Unnamed: 11": null,
      "Unnamed: 12": null
    },
    {
      "Unnamed: 0": "DescriÃ§Ã£o geral",
      "Unnamed: 1": null,
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null,
      "Unnamed: 10": null,
      "Unnamed: 11": null,
      "Unnamed: 12": null
    },
    {
      "Unnamed: 0": "Coluna",
      "Unnamed: 1": "% executada",
      "Unnamed: 2": "CAPEX (Reaj.)",
      "Unnamed: 3": "Data da atualizaÃ§Ã£o",
      "Unnamed: 4": "ResponsÃ¡vel",
      "Unnamed: 5": "Cargo",
      "Unnamed: 6": "Setor",
      "Unnamed: 7": "Riscos Relacionados (Tipo)",
      "Unnamed: 8": "Riscos Relacionados (DescriÃ§Ã£o)",
      "Unnamed: 9": null,
      "Unnamed: 10": null,
      "Unnamed: 11": null,
      "Unnamed: 12": null
    },
    {
      "Unnamed: 0": "DescriÃ§Ã£o do tipo de dado",
      "Unnamed: 1": "% do serviÃ§o executa no dia de atualizaÃ§Ã£o.",
      "Unnamed: 2": "Reajuste do CAPEX total se houver.",
      "Unnamed: 3": "Data da atualizaÃ§Ã£o",
      "Unnamed: 4": "Quem atualizou",
      "Unnamed: 5": "Cargo de quem atualizou",
      "Unnamed: 6": "Setor de quem atualizou",
      "Unnamed: 7": "ClassificaÃ§Ã£o do risco relacionado a prÃ³xima etapa.",
      "Unnamed: 8": "Risco relacionado ao alcance das prÃ³ximas etapas.",
      "Unnamed: 9": null,
      "Unnamed: 10": null,
      "Unnamed: 11": null,
      "Unnamed: 12": null
    },
    {
      "Unnamed: 0": "Dados exemplificativos",
      "Unnamed: 1": 1,
      "Unnamed: 2": 1110000000,
      "Unnamed: 3": null,
      "Unnamed: 4": "Mateus",
      "Unnamed: 5": "Analista",
      "Unnamed: 6": "PPI",
      "Unnamed: 7": "Meio ambiente",
      "Unnamed: 8": null,
      "Unnamed: 9": null,
      "Unnamed: 10": null,
      "Unnamed: 11": null,
      "Unnamed: 12": null
    },
    {
      "Unnamed: 0": null,
      "Unnamed: 1": 0.55,
      "Unnamed: 2": 1120000000,
      "Unnamed: 3": null,
      "Unnamed: 4": "Carlos",
      "Unnamed: 5": "EstagiÃ¡rio",
      "Unnamed: 6": "PPI",
      "Unnamed: 7": "Financeiro",
      "Unnamed: 8": null,
      "Unnamed: 9": null,
      "Unnamed: 10": null,
      "Unnamed: 11": null,
      "Unnamed: 12": null
    },
    {
      "Unnamed: 0": null,
      "Unnamed: 1": null,
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": "Fulano",
      "Unnamed: 5": "TÃ©cnico",
      "Unnamed: 6": "MPOR",
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null,
      "Unnamed: 10": null,
      "Unnamed: 11": null,
      "Unnamed: 12": null
    },
    {
      "Unnamed: 0": "RestriÃ§Ãµes",
      "Unnamed: 1": "Valores em porcentagem.",
      "Unnamed: 2": "Valor monetÃ¡rio",
      "Unnamed: 3": "Data (11/11/2011)",
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": "Lista suspensa com possibilidade de incluir novas opÃ§Ãµes.",
      "Unnamed: 7": "Lista suspensa com possibilidade de incluir novas opÃ§Ãµes.",
      "Unnamed: 8": "DescriÃ§Ã£o mais livre.",
      "Unnamed: 9": null,
      "Unnamed: 10": null,
      "Unnamed: 11": null,
      "Unnamed: 12": null
    }
  ],
  "RelaÃ§Ãµes entre tabelas": [
    {
      "Unnamed: 1": "RELAÃ‡ÃƒO ENTRE OS DADOS",
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null,
      "Unnamed: 10": null
    },
    {
      "Unnamed: 1": "Zona portuÃ¡ria",
      "Unnamed: 2": "UF",
      "Unnamed: 3": "Obj. de ConcessÃ£o",
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": "Chave primÃ¡ria da tabela 00 para os outros cadastros.",
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null,
      "Unnamed: 10": null
    },
    {
      "Unnamed: 1": "Tipo de ServiÃ§o",
      "Unnamed: 2": "Fase",
      "Unnamed: 3": "ServiÃ§o",
      "Unnamed: 4": "DescriÃ§Ã£o",
      "Unnamed: 5": null,
      "Unnamed: 6": "Chave primÃ¡ria da tabela 01 para os outros cadastros.",
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null,
      "Unnamed: 10": null
    },
    {
      "Unnamed: 1": "% executada",
      "Unnamed: 2": "CAPEX (Reaj.)",
      "Unnamed: 3": "Data da atualizaÃ§Ã£o",
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": "Cadastro Ãºnico da tabela de acompanhamento",
      "Unnamed: 7": null,
      "Unnamed: 8": null,
      "Unnamed: 9": null,
      "Unnamed: 10": null
    },
    {
      "Unnamed: 1": "Zona portuÃ¡ria",
      "Unnamed: 2": "UF",
      "Unnamed: 3": "Obj. de ConcessÃ£o",
      "Unnamed: 4": "Tipo de ServiÃ§o",
      "Unnamed: 5": "Fase",
      "Unnamed: 6": "ServiÃ§o",
      "Unnamed: 7": "DescriÃ§Ã£o",
      "Unnamed: 8": "% executada",
      "Unnamed: 9": "CAPEX (Reaj.)",
      "Unnamed: 10": "Data da atualizaÃ§Ã£o"
    },
    {
      "Unnamed: 1": null,
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": "% executada",
      "Unnamed: 9": "CAPEX (Reaj.)",
      "Unnamed: 10": "Data da atualizaÃ§Ã£o"
    },
    {
      "Unnamed: 1": null,
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": "% executada",
      "Unnamed: 9": "CAPEX (Reaj.)",
      "Unnamed: 10": "Data da atualizaÃ§Ã£o"
    },
    {
      "Unnamed: 1": null,
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": "Tipo de ServiÃ§o",
      "Unnamed: 5": "Fase",
      "Unnamed: 6": "ServiÃ§o",
      "Unnamed: 7": "DescriÃ§Ã£o",
      "Unnamed: 8": "% executada",
      "Unnamed: 9": "CAPEX (Reaj.)",
      "Unnamed: 10": "Data da atualizaÃ§Ã£o"
    },
    {
      "Unnamed: 1": null,
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": "% executada",
      "Unnamed: 9": "CAPEX (Reaj.)",
      "Unnamed: 10": "Data da atualizaÃ§Ã£o"
    },
    {
      "Unnamed: 1": null,
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": "% executada",
      "Unnamed: 9": "CAPEX (Reaj.)",
      "Unnamed: 10": "Data da atualizaÃ§Ã£o"
    },
    {
      "Unnamed: 1": null,
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": "Tipo de ServiÃ§o",
      "Unnamed: 5": "Fase",
      "Unnamed: 6": "ServiÃ§o",
      "Unnamed: 7": "DescriÃ§Ã£o",
      "Unnamed: 8": "% executada",
      "Unnamed: 9": "CAPEX (Reaj.)",
      "Unnamed: 10": "Data da atualizaÃ§Ã£o"
    },
    {
      "Unnamed: 1": null,
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": "% executada",
      "Unnamed: 9": "CAPEX (Reaj.)",
      "Unnamed: 10": "Data da atualizaÃ§Ã£o"
    },
    {
      "Unnamed: 1": null,
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": "% executada",
      "Unnamed: 9": "CAPEX (Reaj.)",
      "Unnamed: 10": "Data da atualizaÃ§Ã£o"
    },
    {
      "Unnamed: 1": "Zona portuÃ¡ria",
      "Unnamed: 2": "UF",
      "Unnamed: 3": "Obj. de ConcessÃ£o",
      "Unnamed: 4": "Tipo de ServiÃ§o",
      "Unnamed: 5": "Fase",
      "Unnamed: 6": "ServiÃ§o",
      "Unnamed: 7": "DescriÃ§Ã£o",
      "Unnamed: 8": "% executada",
      "Unnamed: 9": "CAPEX (Reaj.)",
      "Unnamed: 10": "Data da atualizaÃ§Ã£o"
    },
    {
      "Unnamed: 1": null,
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": "% executada",
      "Unnamed: 9": "CAPEX (Reaj.)",
      "Unnamed: 10": "Data da atualizaÃ§Ã£o"
    },
    {
      "Unnamed: 1": null,
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": "% executada",
      "Unnamed: 9": "CAPEX (Reaj.)",
      "Unnamed: 10": "Data da atualizaÃ§Ã£o"
    },
    {
      "Unnamed: 1": null,
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": "Tipo de ServiÃ§o",
      "Unnamed: 5": "Fase",
      "Unnamed: 6": "ServiÃ§o",
      "Unnamed: 7": "DescriÃ§Ã£o",
      "Unnamed: 8": "% executada",
      "Unnamed: 9": "CAPEX (Reaj.)",
      "Unnamed: 10": "Data da atualizaÃ§Ã£o"
    },
    {
      "Unnamed: 1": null,
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": "% executada",
      "Unnamed: 9": "CAPEX (Reaj.)",
      "Unnamed: 10": "Data da atualizaÃ§Ã£o"
    },
    {
      "Unnamed: 1": null,
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": "% executada",
      "Unnamed: 9": "CAPEX (Reaj.)",
      "Unnamed: 10": "Data da atualizaÃ§Ã£o"
    },
    {
      "Unnamed: 1": null,
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": "Tipo de ServiÃ§o",
      "Unnamed: 5": "Fase",
      "Unnamed: 6": "ServiÃ§o",
      "Unnamed: 7": "DescriÃ§Ã£o",
      "Unnamed: 8": "% executada",
      "Unnamed: 9": "CAPEX (Reaj.)",
      "Unnamed: 10": "Data da atualizaÃ§Ã£o"
    },
    {
      "Unnamed: 1": null,
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": "% executada",
      "Unnamed: 9": "CAPEX (Reaj.)",
      "Unnamed: 10": "Data da atualizaÃ§Ã£o"
    },
    {
      "Unnamed: 1": null,
      "Unnamed: 2": null,
      "Unnamed: 3": null,
      "Unnamed: 4": null,
      "Unnamed: 5": null,
      "Unnamed: 6": null,
      "Unnamed: 7": null,
      "Unnamed: 8": "% executada",
      "Unnamed: 9": "CAPEX (Reaj.)",
      "Unnamed: 10": "Data da atualizaÃ§Ã£o"
    }
  ]
};
